# **Arewa Data Science Academy**

Deep Learning Cohort 2.0

Name: Muhammad Usman

Email: muhdusman10@gmail.com

Title: Week 1 Solution

In [2]:
import torch

2. Create a random tensor with shape (7, 7)

In [3]:
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.5362, 0.7528, 0.6229, 0.7769, 0.8767, 0.7265, 0.4424],
        [0.1526, 0.0598, 0.7117, 0.8732, 0.2854, 0.1635, 0.3282],
        [0.7477, 0.1201, 0.1408, 0.3239, 0.0961, 0.1050, 0.8404],
        [0.9965, 0.5522, 0.2830, 0.8900, 0.9790, 0.5597, 0.3179],
        [0.4130, 0.2971, 0.9447, 0.1780, 0.7127, 0.8098, 0.0870],
        [0.5657, 0.3037, 0.2129, 0.2652, 0.8263, 0.2953, 0.8951],
        [0.4613, 0.8359, 0.8679, 0.7914, 0.0174, 0.7693, 0.9970]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
rand_tensor2 = torch.rand(1,7)
rand_tensor2

tensor([[0.7379, 0.0837, 0.5617, 0.2984, 0.8114, 0.2743, 0.8154]])

In [5]:
# Matrix multiplication and transpoding rand tensor 2
result = torch.matmul(rand_tensor, rand_tensor2.T)
result

tensor([[2.3117],
        [1.3220],
        [1.5295],
        [2.4133],
        [1.7847],
        [2.1228],
        [2.1722]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [6]:
# Set manual seed
torch.manual_seed(0)

rand_tensor_1 = torch.rand(7, 7)
rand_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
result1 = torch.matmul(rand_tensor_1, rand_tensor_2.T)
result1

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [7]:
# prompt: Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

if torch.cuda.is_available():
    torch.cuda.manual_seed(0)
    print("GPU available and seed set")
else:
    print("GPU not available")

GPU available and seed set


6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:


In [8]:
# Set the random seed for reproducibility
torch.manual_seed(1234)

# Create two random tensors of shape (2, 3)
tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)

# Check if a CUDA device (GPU) is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move the tensors to the GPU (if available)
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

# Print the tensors
print("Device:", device)
print(tensor1, tensor2)


Device: cuda
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0') tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [11]:
# Check if a CUDA device (GPU) is available
device2 = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move the tensors to the GPU (if available)
tensor1 = tensor1.to(device2)
tensor2 = tensor2.to(device2)

# Perform matrix multiplication.  We need to transpose the second tensor
# to make the dimensions compatible.
result2 = torch.matmul(tensor1, tensor2.T)

# Print the result
print(result2, result2.shape)

tensor([[ 0.5595,  0.4036],
        [-0.5087,  0.2792]], device='cuda:0') torch.Size([2, 2])


8. Find the maximum and minimum values of the output of 7.


In [13]:
# Create a sample tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Find the maximum value
max_value = torch.max(tensor).item()
print("Maximum value:", max_value)

# Find the minimum value
min_value = torch.min(tensor).item()
print("Minimum value:", min_value)


Maximum value: 6
Minimum value: 1


Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
max_index = torch.argmax(tensor)
print("Maximum index:", max_index)

# Find arg min
min_index = torch.argmin(tensor)
print("Minimum index:", min_index)



Maximum index: tensor(5)
Minimum index: tensor(0)


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor_rand = torch.randn(1, 1, 1, 10)

# Print the first tensor and its shape
print("Tensor 1:")
print(tensor_rand)
print("Shape:", tensor_rand.shape)



# Remove single dimensions
tensor_remove = tensor_rand.squeeze()


# Print out tensors and their shapes
print("\nTensor 2:")
print(tensor_remove)
print("Shape:", tensor_remove.shape)


Tensor 1:
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Shape: torch.Size([1, 1, 1, 10])

Tensor 2:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
Shape: torch.Size([10])
